-- Run this after schema.sql to populate the exercise library
-- Run in Supabase SQL Editor

INSERT INTO exercises (name, muscle_group) VALUES
  ('Bench Press', 'Chest'),
  ('Incline Bench Press', 'Chest'),
  ('Cable Fly', 'Chest'),
  ('Chest Dip', 'Chest'),
  ('Deadlift', 'Back'),
  ('Pull Up', 'Back'),
  ('Lat Pulldown', 'Back'),
  ('Barbell Row', 'Back'),
  ('Cable Row', 'Back'),
  ('Squat', 'Legs'),
  ('Leg Press', 'Legs'),
  ('Romanian Deadlift', 'Legs'),
  ('Leg Curl', 'Legs'),
  ('Leg Extension', 'Legs'),
  ('Calf Raise', 'Legs'),
  ('Shoulder Press', 'Shoulders'),
  ('Lateral Raise', 'Shoulders'),
  ('Front Raise', 'Shoulders'),
  ('Face Pull', 'Shoulders'),
  ('Bicep Curl', 'Arms'),
  ('Hammer Curl', 'Arms'),
  ('Preacher Curl', 'Arms'),
  ('Tricep Pushdown', 'Arms'),
  ('Skull Crusher', 'Arms'),
  ('Overhead Tricep Extension', 'Arms'),
  ('Plank', 'Core'),
  ('Cable Crunch', 'Core'),
  ('Hanging Leg Raise', 'Core'),
  ('Ab Wheel Rollout', 'Core'),
  ('Treadmill', 'Cardio'),
  ('Rowing Machine', 'Cardio'),
  ('Stairmaster', 'Cardio');
