export const theme = {
  colors: {
    background: '#FAF7F2',
    backgroundAlt: '#F1EAE0',
    card: '#FFFFFF',
    cardWarm: '#FDFBF7',
    text: '#2D2D2D',
    textMuted: '#9B968E',
    accent: '#C9826B',
    accentSoft: '#ECD3CB',
    secondary: '#8FA68A',
    secondarySoft: '#D8E0D6',
    highlight: '#E8C46A',
    caramel: '#E8C46A',
    border: '#E9E2D6',
    success: '#8FA68A',
    danger: '#B5573F',
    tabBar: '#FDFBF7',
    tabBarBorder: '#E9E2D6',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  radius: {
    sm: 12,
    md: 18,
    lg: 26,
    full: 9999,
  },
  fontSize: {
    xs: 11,
    sm: 13,
    md: 15,
    lg: 17,
    xl: 20,
    xxl: 26,
    xxxl: 34,
  },
  fonts: {
    display: 'InstrumentSerif_400Regular',
    displayBold: 'InstrumentSerif_400Regular',
    displayItalic: 'InstrumentSerif_400Regular_Italic',
    body: 'Inter_400Regular',
    bodyMedium: 'Inter_500Medium',
    bodySemiBold: 'Inter_600SemiBold',
    bodyBold: 'Inter_700Bold',
    bodyExtraBold: 'Inter_800ExtraBold',
  },
  shadow: {
    soft: {
      shadowColor: '#2D2D2D',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 6,
      elevation: 2,
    },
    card: {
      shadowColor: '#2D2D2D',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.08,
      shadowRadius: 16,
      elevation: 4,
    },
    floating: {
      shadowColor: '#2D2D2D',
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.16,
      shadowRadius: 28,
      elevation: 10,
    },
  },
}
